project:
  type: default
  output-dir: docs
  render:
    - index.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 6
    crossref:
      custom:
        - kind: float
          reference-prefix: "Exercise"
          key: "exr"