project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Biostatistics - Research School in Clinical Psychiatry"
  page-navigation: true
  repo-url: https://github.com/biostatistics-psychiatry/lab-materials
  repo-actions: [edit, issue]

  sidebar:
    title: "Biostatistics - II"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 1

    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: Overview

      - section: "Chapters"
        contents:
          - href: chapters/regression-intro.qmd
            text: Introduction to Linear and Quantile Regression in R
          - href: chapters/regression-one-binary-predictor.qmd
            text: One Binary Predictor
          - href: chapters/regression-one-cat-pred.qmd
            text: One Categorical Predictor
          - href: chapters/regression-one-numeric-predictor.qmd
            text: One Numeric Predictor
          - href: chapters/regression-two-binary-predictors.qmd
            text: Two Binary Predictors
          - href: chapters/regression-binary-and-numeric-predictors.qmd
            text: One Binary and One Numeric Predictor
            
      - section: "Labs"
        contents:
          - href: labs/template.qmd
            text: Template

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 6
    crossref:
      custom:
        - kind: float
          reference-prefix: "Exercise"
          key: "exr"